# Generated by Django 5.1.3 on 2024-11-07 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_notification_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='product',
        ),
    ]
