# Generated by Django 5.1.3 on 2024-11-07 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_cart_status_remove_cart_updated_at_cart_boxes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='store_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
